DROP TABLE IF EXISTS income CASCADE;
DROP TABLE IF EXISTS expense CASCADE;

CREATE TABLE income (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  amount NUMERIC NOT NULL,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
  day INTEGER NOT NULL CHECK (day BETWEEN 1 AND 31),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  income_budgets_id INTEGER REFERENCES income_budgets(id) ON DELETE CASCADE
);

CREATE TABLE expense (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  amount NUMERIC NOT NULL,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
  day INTEGER NOT NULL CHECK (day BETWEEN 1 AND 31),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  expense_budgets_id INTEGER REFERENCES expense_budgets(id)ON DELETE CASCADE
);
